/** Configuration file */

module.exports = {
    FB_PAGE_TOKEN: 'XXXXXXXXXXXXX',
    FB_PAGE_ID: 'XXXXXXXXXXXXX',
    FB_APP_SECRET: 'XXXXXXXXXXXXX',
    FB_VERIFY_TOKEN: 'XXXXXXXXXXXXX',
    WIT_TOKEN: 'XXXXXXXXXXXXX',
    OPEN_WEATHER_API_KEY: 'XXXXXXXXXXXXX',
    NEWS_API_KEY: 'XXXXXXXXXXXXX',
    PORT:3000,
};
